### ISSUE TITLE
Long time to open the app

### ISSUE THREAD

**Issue by mashavct** [NaserElziadna/doddle#4]
Hi! Really nice app, but I found 1 bug. Steps to reproduce:
1. Clear app's data
2. Open it. It takes a lot of time (about 12 seconds)

My mobile device: Xiaomi 11 Lite 5G NE
MIUI version: 13.0.3.0
Android version: 12 SKQ1.211006.001
Doddle version: 1.0.2

https://user-images.githubusercontent.com/108602416/181068946-55f6b4d9-a4ad-49d3-b60b-1e2fe9a24d41.mp4

**Comment by NaserElziadna** [comment]
hi @mashavct ,
thanks for reporting the issue ,
i found that the app  takes too long to open only when launch for the very first time.(maybe it's a flutter thing!!)

after that i could not reproduce the issue.

any Pull Requests are welcomed
